### ISSUE TITLE
No access to the Razberry card 

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [Z-Wave-Me/ha-z-wave-me-addon#17]
Hi,

I get an error when trying to access the Razberry card inside of the add-on.

![Skärmavbild 2023-04-09 kl  09 20 42](https://user-images.githubusercontent.com/200246/230759922-ed9b8f47-7343-4a3a-aa80-0d987a6ea87f.png)

If I log in as root to HA via ssh, the permissions seem ok
```

# ls -al /dev/ttyAMA0 
crw-rw----    1 root     dialout   204,  64 Apr  7 14:48 /dev/ttyAMA0
```

as long as the add-on is accessing the device is part of `dialup` ? 

What do I need to do to pass it through to the add-on appropriately?

**Comment by PoltoS** [comment]
Please make sure the correct port is set in add-on settings in HA. And please show the log so we can see the error.

Also, check that no other s/w is accessing this port

**Comment by PoltoS** [comment]
Hm..

1) Do you use Remote Z-Way app? Or some other app connecting to another Z-Way (or itself?!)
`Can not make request: Timeout was reached http://10.0.1.111:8083/ZAutomation/api/v1/devices?since=0` 

2) Indeed, this `[config]  Read/write access to config folder is not granted` is a problem. Would it be possible to enable remote support and provide us the id and password? We will check what is wrong here.

Sure you are using our latest version 4.0.3 from add-on stores?

**Comment by FredrikKarlssonSpeech** [comment]
Yes,I am using the 4.0.3 version.

Please ignore the  timeout error messages. Indeed I am using the remote Z-way app, and IP address was wrong.

The config read/write permission issue persists though, so I am activating the remote access and will send you information.

**Comment by msazanov** [comment]
@FredrikKarlssonSpeech Hello, the problem has been found and will be fixed very soon, it manifests itself in 2 cases, when restoring a backup copy from another system or resetting the system to factory settings.
If you see this problem after restoring the backup, then use our telegram bot to convert backups from other instalation https://t.me/BackUpConverter_bot
If you encounter this problem after resetting to factory settings, then simply reinstall the addon.

**Comment by PoltoS** [comment]
Fixed in https://github.com/Z-Wave-Me/ha-z-wave-me-addon/pull/20

**Comment by usddsu** [comment]
Hi,
i get the same error after restoring my backup from Zway 4.1.1 under Rpi3b

config]  Read/write access to config folder is not granted

i‘m using HA 2023.10.3 as a VM under Proxmox, UZB1 (dev/ttyACM0) , UZB1 is passthrough from pve and seems ok in HA

i have no telegram to use the backupconvert_bot, what can i do ?

**Comment by PoltoS** [comment]
@msazanov can describe you how to make it manually
