### ISSUE TITLE
Update to v4.1.3 - Error while loading shared libraries: libgattlib.so

### ISSUE THREAD

**Issue by krfr** [Z-Wave-Me/ha-z-wave-me-addon#38]
After update from 4.1.0 to 4.1.3 i got following message:

"INFO: Starting Z-Way server
./z-way-server: error while loading shared libraries: libgattlib.so: cannot open shared object file: No such file or directory"

I use
Core 2024.5.3 / Supervisor 2024.05.1 / Frontend 20240501.1

**Comment by PoltoS** [comment]
Hello! This was fixes today by publishing the update Z-Way build. I assume, you are on Ubuntu or Debian x64, right? Just rebuild your docker clearing the docker cache first. This should work.

**Comment by usddsu** [comment]
Hello,
same problem here, i‘m using HA as a VM on Proxmox, what to do ?

**Comment by PoltoS** [comment]
Please le us know the OS type and CPU

**Comment by usddsu** [comment]
Hello,Intel Nuc i5Proxmox 8.2.2HA as VMHA Core 2024.5.3Supervisor 2024.05.1OS 12.3Frontend 20240501.1kindly regardsUlfAm 15.05.2024 um 12:49 schrieb Poltorak Serguei ***@***.***>:﻿
Please le us know the OS type and CPU

**Comment by PoltoS** [comment]
So, x64? Ok, we check it and get back to you.

**Comment by krfr** [comment]
> Hello! This was fixes today by publishing the update Z-Way build. I assume, you are on Ubuntu or Debian x64, right? Just rebuild your docker clearing the docker cache first. This should work.


Hi and thanks for reply.
Yes, I'm running Debian 11 x86

But unfortunately I don't really understand your answer or solution to the problem.

Maybe rebuilding docker would work, but can't see that you publishing the update Z-Way build after the time I did my update to HA, so docker should be the same version even after a rebuild.
Or maybe I misunderstood your answer. Are you able to guide me a bit more because I don't really know which way is best to rebuild docker and get a solution to this.

**Comment by PoltoS** [comment]
Yes, a rebuild should fix it. The new Z-Way should be downloaded during the docker build

**Comment by krfr** [comment]
> Yes, a rebuild should fix it. The new Z-Way should be downloaded during the docker build

Ok, But I tested earlier to uninstall Z-Way from Home Assistant GUI and also remove image with docker rmi image-id command, and then make a new install from HA GUI... Same problem.

**Comment by krfr** [comment]
As I wrote before, I don't know how to do a rebuild... Any tips on how to do it?

**Comment by msazanov** [comment]
Hello, the problem has been discovered and we will fix it soon in the main repository, while you can use the test one. You can switch to the main repository later.
https://github.com/msazanov/ha-z-wave-me-addon

**Comment by PoltoS** [comment]
Hello!

Fixed. Just re-install the add-on (delete the old first so it builds/downloads it again)

This was tested to work:
```
docker pull ghcr.io/z-wave-me/amd64-ha-z-wave-me-addon:v4.1.3
docker run ghcr.io/z-wave-me/amd64-ha-z-wave-me-addon:v4.1.3

```

**Comment by krfr** [comment]
> Hello!
> 
> Fixed. Just re-install the add-on (delete the old first so it builds/downloads it again)
> 
> This was tested to work:
> 
> ```
> docker pull ghcr.io/z-wave-me/amd64-ha-z-wave-me-addon:v4.1.3
> docker run ghcr.io/z-wave-me/amd64-ha-z-wave-me-addon:v4.1.3
> ```
> 
> Please confirm to close the issue.

Works now. Thanks!

**Comment by usddsu** [comment]
Works now, 

Thanks!

**Comment by PoltoS** [comment]
Thanks for confirming!
