### ISSUE TITLE
zbee - Read/write access to config folder is not granted

### ISSUE THREAD

**Issue by krfr** [Z-Wave-Me/ha-z-wave-me-addon#42]
Have problem to get Z-station to work with zigbee in Z-Wave.Me Add-on v4.1.3.
z-wave work like a charm.

Cannot start Zigbee binding: Error: Invalid config
I use serial port /dev/ttyUSB1

When i check log for Z-Wave.Me Add-on in HA i can se following error;

Loading module Zigbee from modules/Zigbee
Executing script: /*** Zigbee Binding module
Instantiating module 15 from class Zigbee
--- Starting module Zigbee Network Access
Removing job: Set controller node information frame
Read/write access to config folder is not granted
Error: Invalid config
Trying to restart Zigbee binding (zbee) in 10 seconds
..
..
..
Restarting Zigbee binding (zbee)
Read/write access to config folder is not granted
Error: Invalid config
Trying to restart Zigbee binding (zbee) in 10 seconds
... and so on

Running on Debian
Core 2024.6.2
Supervisor 2024.06.0
Frontend 20240610.0

**Comment by PoltoS** [comment]
Hello!

I'll pass it to our support team, we will check it and get back to you.

**Comment by PoltoS** [comment]
Z-Way saves its version on shutdown, so overrides your changes. You should either:
1) stop Z-Way and edit the file
2) use Z-Way to alter it and save:
```
http://localhost:8083/JS/Run/controller.instances.filter(function(i){return i.moduleId=="Zigbee"})[0].params.config="configs/config"
http://localhost:8083/JS/Run/controller.saveConfig(true)```

**Comment by krfr** [comment]
@PoltoS Your solution worked, so now zigbee works with z station and error messages are gone. Thanks for the help.

This issue is resolved and can be closed.

**Comment by PoltoS** [comment]
Thanks for your feed back. A five ⭐ rating is appreciated (if you bought it on Amazon) ;)
